### ISSUE TITLE
Update axios version (critical security vulnerability)

### ISSUE THREAD

**Issue by julioneljunior** [thblckjkr/insomnia-plugin-gist-sync#4]
Hello,
When trying to install the plugin on insomnia, this error is displayed.

> Failed to install insomnia-plugin-sync-gist-multiprovider
> 
> There may be an issue with the plugin itself, as a note you can discover and install plugins from the Plugin Hub.
> Additionl Information
> Error: Yarn error warning insomnia-plugin-sync-gist-multiprovider > axios@0.19.2: Critical security vulnerability fixed in v0.21.1. For more information, see https://github.com/axios/axios/pull/3410
> 
>     at file:///C:/Users/David%20Dev/AppData/Local/insomnia/app-2020.5.2/resources/app.asar/bundle.js:103518:16
>     at ChildProcess.exithandler (child_process.js:295:7)
>     at ChildProcess.emit (events.js:223:5)
>     at maybeClose (internal/child_process.js:1021:16)
>     at Process.ChildProcess._handle.onexit (internal/child_process.js:283:5)`

I downloaded the code and updated the library version and everything worked again.

thanks for the plugin!

**Comment by thblckjkr** [comment]
Solved on release v0.2.2

Thanks for the heads up! It is (hopefully) now solved, and already installable on the insomnia client.
