### ISSUE TITLE
Insomnia is unable to sync in github or gitlab

### ISSUE THREAD

**Issue by joeydash** [thblckjkr/insomnia-plugin-gist-sync#5]
{
  "_type": "export",
  "__export_format": 4,
  "__export_date": "2021-09-23T04:39:16.139Z",
  "__export_source": "insomnia.desktop.app:v2021.5.3",
  "resources": []
}

**Comment by thblckjkr** [comment]
I noticed the same behavior, I haven't had the time to debug it but it's on my bucket list for the next week.

I'm pretty sure it's something related to the recent version change of insomnia, but I have not confirmed it.

**Comment by kobenguyent** [comment]
hi @thblckjkr @joeydash I have managed to patch the issue.

**Comment by thblckjkr** [comment]
Hi! Thanks @PeterNgTr.

It is in process of releasing and the fix should be published in a couple of minutes.
